// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Color     string
	CreatedAt time.Time
}

type Expense struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CategoryID  uuid.NullUUID
	Amount      string
	Description string
	Date        time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
